---
version: '3.3'
services:
    mongodb:
      image: mongo:4.1
      container_name: mongodb
      hostname: mongodb

    broker:
      build:
        context: .
        labels:
           - "Project.Name=Paraffin"
           - "Module.Name=broker"
           - "version=0.02"
           - "maintainer=rafiee1001@gmail.com"
        dockerfile: Dockerfile
      image: broker
      container_name: broker
      hostname: broker
      command: node index.js
      expose:
        - 1883
        - 3000
        - 2345
      environment:
        NODE_ENV: production
        PROCESS_TYPE: direct-mongo
        APP_NAME: Paraffin Broker
        DB_PONTE_NAME: mongodb://mongodb:27017/ponte
        DB_AUTH_URL: mongodb://mongodb:27017/paraffin
        DB_AUTH_COLLECTION: authBroker
        MQTT_PORT: 1883
        HTTP_PORT: 3000
        COAP_PORT: 5683
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      env_file: .env
      depends_on:
        - mongodb
